version: '2.4'

services:
  bot:
    container_name: "rendang-bot"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    network_mode: 'host'
